---

#开启动态网关服务发现
#ribbon:
#  eureka:
#    enabled: true

---

# 暴露actuator所有端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

---

# 配置zuul路由表，静态路由
#zuul:
#  prefix: /zuul #为zuul设置一个公共的前缀
#  ignoredServices: '*' # 不匹配哪些些路径
#  routes:
#    routes-1: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
#      path: /${zuul.routes.routes-1.serviceId}/** #匹配/test/** 均路由到cloud-client
#      serviceId: ays
#    routes-2: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
#      path: /${zuul.routes.routes-2.serviceId}/** #匹配/test/** 均路由到cloud-client
#      serviceId: ads

---

#基于静态路由节点的ribbon负载均衡配置
#ace-admin:
#  ribbon:
#    listOfServers: 127.0.0.1:8767

#security:
#    user:
#        name: admin
#        password: admin
#        role: USER

---

#避免第一次调用失败
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false #禁用超时
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000

---

#请求和响应GZIP压缩支持
#feign:
#  hystrix:
#    enable: true # feign的自带断路器，默认为false，可以去掉
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true